parameters:
  - name: ServiceConnection
    displayName: Service Connection Name Follows Below:-
    default: conn-sb-qa-we-1
    values:
      - conn-sb-qa-we-1
  - name: image
    displayName: PoolImage
    default: windows-latest
    type: string
    values:
      - windows-latest
      - ubuntu-latest

variables:
- group: startstopqa
- name: clientidvar
  value: $[variables.clientid]
- name: secretvaluevar
  value: $[variables.secretvalue]
- name: tenantidvar
  value: $[variables.tenantid]
- name: subscriptionvar
  value: $[variables.subscription]
- name: BuildAgent
  value: ${{ parameters.image }}
- name: Environment
  value: QA
- name: ResourceGroup
  value: rg-sb-gen-qa-we-2
- name: StorageAccount
  value: stsbgenqawe2
- name: Container
  value: stblc-sb-cnt-qa-we-2
- name: TfstateFile
  value: qatf1/terraform.tfstate

trigger:
- main

pool:
  vmImage: $(BuildAgent)

stages:
- stage: CLIinstall
  jobs:
  - job: cliinstall
    displayName: cliinstall     
    steps:  
    # Install Terraform Installer in the Build Agent:-
    - task: TerraformInstaller@0
      displayName: Install terrform version - LATEST
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: TERRAFORM INIT
      inputs:
        provider: 'azurerm'
        command: 'init'
        #workingDirectory: '$(workingDir)' # Az DevOps can find the required Terraform code
        backendServiceArm: '${{ parameters.ServiceConnection }}'
        backendAzureRmResourceGroupName: '$(ResourceGroup)' 
        backendAzureRmStorageAccountName: '$(StorageAccount)'
        backendAzureRmContainerName: '$(Container)'
        backendAzureRmKey: '$(TfstateFile)'

    
- stage: import
  displayName: import
  jobs:
  - job: import
    displayName:  import
    steps:

    - powershell: |
       az login --service-principal -u $(clientidvar) -p $(secretvaluevar) --tenant $(tenantidvar)
       az account set --subscription $(subscriptionvar)
       terraform init
       terraform import azurerm_virtual_machine_extension.clo_db_dsc-extension /subscriptions/ab25a1c8-c966-4d16-8f19-d36b27af1ea0/resourceGroups/rg-sb-clo-db-qa-we-1/providers/Microsoft.Compute/virtualMachines/vmclodbqawe1/extensions/dsc-extension 