parameters:
  - name: ServiceConnection
    displayName: Service Connection Name Follows Below:-
    default: tes-vm-sc
    values:
      - tes-vm-sc
  - name: image
    displayName: PoolImage
    default: windows-latest
    type: string
    values:
      - windows-latest
      - ubuntu-latest
variables:
  ResourceGroup: mcmd-dev-rg
  StorageAccount: samlinkstorage1234
  Container: test-vm
  TfstateFile: test-vm/terraform.tfstate
  BuildAgent: ${{ parameters.image }}
  #WorkingDir: $(System.DefaultWorkingDirectory)/variables
  #Target: $(build.artifactstagingdirectory)/AMTF
  Environment: test
  group: password
 # Artifact: AM
 
trigger:
- main

pool:
  vmImage: $(BuildAgent)

stages:
- stage: PLAN
  jobs:
  - job: PLAN
    displayName: PLAN     
    steps:  
    # Install Terraform Installer in the Build Agent:-
    - task: TerraformInstaller@1
      displayName: Install terrform version - LATEST
      inputs:
        terraformVersion: 'latest'
   # Terraform Init:-
    - task: TerraformTaskV4@4
      displayName: TERRAFORM INIT
      inputs:
        provider: 'azurerm'
        command: 'init'
        #workingDirectory: '$(workingDir)' # Az DevOps can find the required Terraform code
        backendServiceArm: '${{ parameters.ServiceConnection }}'
        backendAzureRmResourceGroupName: '$(ResourceGroup)' 
        backendAzureRmStorageAccountName: '$(StorageAccount)'
        backendAzureRmContainerName: '$(Container)'
        backendAzureRmKey: '$(TfstateFile)'
    - task: TerraformTaskV4@4
      displayName: 'terraform import env'
      inputs:
        command: import
        workingDirectory: '$(workingDir)'
        resourceAddress: azurerm_virtual_machine_extension.clo_db_dsc-extension  # The resource type and name in your .tf file
        resourceId: '/subscriptions/ab25a1c8-c966-4d16-8f19-d36b27af1ea0/resourceGroups/rg-sb-clo-db-qa-we-1/providers/Microsoft.Compute/virtualMachines/vmclodbqawe1/extensions/dsc-extension'  # The Azure object id for the Resource Group (see with `az group list` in Powershell)
        