parameters:
  - name: ServiceConnection
    displayName: Service Connection Name Follows Below:-
    default: tes-vm-sc
    values:
      - tes-vm-sc
  - name: image
    displayName: PoolImage
    default: windows-latest
    type: string
    values:
      - windows-latest
      - ubuntu-latest

variables:
  ResourceGroup: mcmd-dev-rg
  StorageAccount: samlinkstorage1234
  Container: test-vm
  TfstateFile: test-vm/terraform.tfstate
  BuildAgent: ${{ parameters.image }}
  Environment: test

trigger:
- main

pool:
  vmImage: $(BuildAgent)

stages:
- stage: PLAN
  jobs:
  - job: PLAN
    displayName: PLAN     
    steps:  
    # Install Terraform Installer in the Build Agent:-
    - task: TerraformInstaller@0
      displayName: Install terrform version - LATEST
      inputs:
        terraformVersion: 'latest'
    - powershell: |
        az login --service-principal -u $(clientidvar) -p $(secretvaluevar) --tenant $(tenantidvar)
        az account set --subscription $(subscriptionvar)
        terraform init
        terraform import azurerm_virtual_machine_extension.clo_db_dsc-extension /subscriptions/ab25a1c8-c966-4d16-8f19-d36b27af1ea0/resourceGroups/rg-sb-clo-db-qa-we-1/providers/Microsoft.Compute/virtualMachines/vmclodbqawe1/extensions/dsc-extension
        