parameters:
  - name: ServiceConnection
    displayName: Service Connection Name Follows Below:-
    default: tes-vm-sc
    values:
      - tes-vm-sc
  - name: image
    displayName: PoolImage
    default: windows-latest
    type: string
    values:
      - windows-latest
      - ubuntu-latest

trigger:
- none      

- task: AzureCLIScript@1
  inputs:
    azureSubscription: 'tes-vm-sc'
    scriptType: 'inlineScript'
    inlineScript: |
      .\install-windows-features.ps1
