schedules:
- cron: '44 10 * * 1-5'
  displayName: Weekday Starting Schedule
  branches:
    include:
      - 'main'
  always: true
 
- cron: '00 17 * * *'
  displayName: Daily Stopping Schedule
  branches:
    include:
      - 'main'
  always: true
 
parameters:
  - name: ServiceConnection
    displayName: Service Connection Name Follows Below:-
    default: tes-vm-sc
    values:
      - tes-vm-sc
  - name: image
    displayName: PoolImage
    default: windows-latest
    type: string
    values:
      - windows-latest
      - ubuntu-latest
  - name: action
    displayName: Start/Stop vms
    type: string
    values:
    - start
    - stop
    - scheduled # Dummy value for scheduler
    default: scheduled
 
variables:
- group: startstop
- name: BuildAgent
  value: ${{ parameters.image }}
- name: Environment
  value: test
-name: clientid
  value: $[variables.clientid]
-name: secretvalue
  value: $[variables.secretvalue]
-name: tenantid
  value: $[variables.tenantid]
-name: subscription
  value: $[variables.subscription]  
 
trigger:
- none
 
pool:
  vmImage: $(BuildAgent)
 
 
stages:
- ${{ if or(eq(parameters.action, 'stop'),  eq(variables['Build.CronSchedule.DisplayName'], 'Daily Stopping Schedule')) }}:
  - stage: stop
    displayName: Stop
    jobs:
    - job: Stop_vms
      displayName:  Stopping vms
      steps:

      - powershell: |
          az login --service-principal -u $(clientid) -p $(secretvalue) --tenant $(tenantid)
          az account set --subscription $(subscription)
          $results = az vm list --query "[].id" --output json | ConvertFrom-Json
          Write-Host "VM IDs: $($results -join ', ')"  # Add this line for debugging
          foreach ($vm_id in $results) {
           az vm deallocate --no-wait --ids $vm_id
          }
        displayName: 'Stop VMs' 
 
- ${{ if or(eq(parameters.action, 'start'), eq(variables['Build.CronSchedule.DisplayName'], 'Weekday Starting Schedule')) }}:
  - stage: start
    displayName: Start
    jobs:
    - job: Start_vms
      displayName:  Starting vms
      steps:
 
      - powershell: |
          az login --service-principal -u $(clientid) -p $(secretvalue) --tenant $(tenantid)
          az account set --subscription $(subscription)
          $results = az vm list --query "[].id" --output json | ConvertFrom-Json
          Write-Host "VM IDs: $($results -join ', ')"  # Add this line for debugging
          foreach ($vm_id in $results) {
           az vm start --no-wait --ids $vm_id
          }
        displayName: 'Start VMs' 