schedules:
- cron: '45 06 * * 1-5'  # 3 AM IST, Mon-Fri
  displayName: Weekday Starting Schedule
  branches:
    include:
      - 'main'
 
- cron: '32 14 * * *'  # 4 PM IST, Daily
  displayName: Daily Stopping Schedule
  branches:
    include:
      - 'main'
 
parameters:
  - name: ServiceConnection
    displayName: Service Connection Name Follows Below:-
    default: tes-vm-sc
    values:
      - tes-vm-sc
  - name: image
    displayName: PoolImage
    default: windows-latest
    type: string
    values:
      - windows-latest
      - ubuntu-latest
  - name: action
    displayName: Start/Stop vms
    type: string
    values:
    - start
    - stop
    - scheduled # Dummy value for scheduler
    default: scheduled
 
variables:
- name: BuildAgent
  value: ${{ parameters.image }}
- name: Environment
  value: test
 
trigger:
- test
 
pool:
  vmImage: $(BuildAgent)
 
 
stages:
- ${{ if or(eq(parameters.action, 'stop'),  eq(variables['Build.CronSchedule.DisplayName'], 'Daily Stopping Schedule')) }}:
  - stage: stop
    displayName: Stop
    jobs:
    - job: Stop_vms
      displayName:  Stopping vms
      steps:
 
      - powershell: |
          az login --service-principal -u f5735f06-8a24-4ba4-9565-831b7dc064dc -p uk18Q~DoHdKK0Z2o_cTnLX5yk4tw~oC9SIIb1dyJ --tenant aa71b1b3-ce80-489f-b318-f42d6dd05d19
          az account set --subscription f8a41613-4251-4981-af4d-85100623c8a4
          $results = az vm list --query "[].id" --output json | ConvertFrom-Json
          Write-Host "VM IDs: $($results -join ', ')"  # Add this line for debugging
          foreach ($vm_id in $results) {
           az vm deallocate --no-wait --ids $vm_id
          }
        displayName: 'Stop VMs' 
 
- ${{ if or(eq(parameters.action, 'start'), eq(variables['Build.CronSchedule.DisplayName'], 'Weekday Starting Schedule')) }}:
  - stage:
    displayName: Start
    jobs:
    - job: Start_vms
      displayName:  Starting vms
      steps:
 
      - powershell: |
          az login --service-principal -u f5735f06-8a24-4ba4-9565-831b7dc064dc -p uk18Q~DoHdKK0Z2o_cTnLX5yk4tw~oC9SIIb1dyJ --tenant aa71b1b3-ce80-489f-b318-f42d6dd05d19
          az account set --subscription f8a41613-4251-4981-af4d-85100623c8a4
          $results = az vm list --query "[].id" --output json | ConvertFrom-Json
          Write-Host "VM IDs: $($results -join ', ')"  # Add this line for debugging
          foreach ($vm_id in $results) {
           az vm start --no-wait --ids $vm_id
          }
        displayName: 'Start VMs' 